name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! Saw that this is your first issue. Wanted to say welcome!'
        pr-message: 'MHi there! Saw that this is your first PR. Wanted to say welcome and thank you for any contributions you made!'
